// sdk_dumper_il2cpp.cpp — IL2CPP → Assembly-CSharp.cs emitter (Phase 10 production).
//
// Drives platform/mem_probe engine adapter: attach target pid, detect engine,
// enumerate class names / il2cpp_* symbols, emit an Il2CppDumper-style
// C#-like header. Streaming write with 10k-name safety cap.

#include "sdk_dumper_base.h"

#include "sao/core/process.h"
#include "sao/mem_probe/engine/adapter.h"

#include <cstdio>
#include <filesystem>
#include <fstream>
#include <vector>

namespace fs = std::filesystem;

namespace sao::ai_editor::sdk_dumper {

namespace {

class Il2CppDumper : public DumperBase {
public:
    DumpKind kind() const override { return DumpKind::IL2CPP; }
    DumpResult dump(const DumpConfig& cfg) override {
        DumpResult r;
        if (cfg.output_dir.empty()) {
            r.error_message = "output_dir required";
            return r;
        }
        if (cfg.target_pid == 0) {
            r.error_message = "target_pid required";
            return r;
        }
        fs::path out = fs::path(cfg.output_dir) / "Assembly-CSharp.cs";
        std::error_code output_error;
        if (fs::exists(out, output_error)) {
            if (output_error || fs::is_directory(out, output_error)) {
                r.error_message = "cannot remove stale output file";
                return r;
            }
            output_error.clear();
            fs::remove(out, output_error);
            if (output_error) {
                r.error_message = "cannot remove stale output file";
                return r;
            }
        } else if (output_error) {
            r.error_message = "cannot inspect stale output file";
            return r;
        }
        std::error_code ec;
        fs::create_directories(cfg.output_dir, ec);
        sao_core_process_handle_t handle = nullptr;
        if (sao_core_process_open(cfg.target_pid,
                                   SAO_PROCESS_ACCESS_INFO | SAO_PROCESS_ACCESS_READ,
                                   &handle) != SAO_STATUS_OK ||
            handle == nullptr) {
            r.error_message = "cannot open target process";
            return r;
        }
        sao_memprobe_engine_kind_t kind = sao_memprobe_engine_detect(handle);
        if (kind != SAO_MEMPROBE_ENGINE_IL2CPP) {
            sao_core_process_close(handle);
            r.error_message = "target is not IL2CPP";
            return r;
        }
        auto* adapter = sao_memprobe_engine_open(handle, SAO_MEMPROBE_ENGINE_IL2CPP);
        if (adapter == nullptr) {
            sao_core_process_close(handle);
            r.error_message = "il2cpp adapter open failed";
            return r;
        }

        // Enumerate up to 10k class-like names.
        const uint32_t class_cap = std::min<uint32_t>(cfg.max_classes, 10'000);
        std::vector<uint32_t> offsets(class_cap);
        std::vector<char> names(class_cap * 64);
        size_t off_count = 0;
        size_t names_used = 0;
        sao_status_t st = sao_memprobe_engine_list_classes(
            adapter, offsets.data(), class_cap, &off_count, names.data(),
            names.size(), &names_used);

        {
            std::ofstream fs_out(out);
            if (!fs_out) {
                sao_memprobe_engine_close(adapter);
                sao_core_process_close(handle);
                r.error_message = "cannot open output file";
                return r;
            }
            fs_out << "// Auto-generated by SAO Auto AI Editor SDK dumper.\n"
                   << "// Target PID: " << cfg.target_pid << "\n"
                   << "// Engine: IL2CPP\n"
                   << "// Enumerated: " << off_count << " classes/symbols\n\n";
            if (st != SAO_STATUS_OK) {
                fs_out.close();
                std::error_code remove_error;
                fs::remove(out, remove_error);
                sao_memprobe_engine_close(adapter);
                sao_core_process_close(handle);
                r.error_message = "IL2CPP class enumeration failed";
                return r;
            }
            for (size_t i = 0; i < off_count; ++i) {
                const char* name = names.data() + offsets[i];
                fs_out << "// class " << name << " {}\n";
            }
            fs_out.flush();
            const bool output_ok = fs_out.good();
            fs_out.close();
            if (!output_ok || !fs_out.good()) {
                std::error_code remove_error;
                fs::remove(out, remove_error);
                sao_memprobe_engine_close(adapter);
                sao_core_process_close(handle);
                r.error_message = "IL2CPP dump output write failed";
                return r;
            }
        }
        sao_memprobe_engine_close(adapter);
        sao_core_process_close(handle);
        if (!fs::exists(out)) {
            r.error_message = "IL2CPP dump output missing";
            return r;
        }
        r.ok = true;
        r.output_files.push_back(out.string());
        r.class_count = static_cast<uint32_t>(off_count);
        return r;
    }
};

} // namespace

DumperBase* create_il2cpp() { return new Il2CppDumper(); }

} // namespace sao::ai_editor::sdk_dumper
