using System.Linq;
using System.Reflection;
using Google.Protobuf;

namespace SaoAuto.Proto;

/// <summary>
/// Surface for the canonical Star.* protobuf bindings generated by Grpc.Tools
/// from <c>Protos/star_resonance.proto</c>. Acts as the smoke test entry that
/// proves codegen wired through end-to-end.
/// </summary>
public static class ProtoPortStatus
{
    public const string CanonicalProtoFile = "star_resonance.proto";

    /// <summary>
    /// Number of generated <see cref="IMessage"/> types in the Star namespace.
    /// </summary>
    public static int GeneratedMessageCount { get; } = CountGenerated();

    /// <summary>
    /// True when at least one <c>Star.*</c> protobuf message type was generated
    /// at build time.
    /// </summary>
    public static bool CodegenAvailable => GeneratedMessageCount > 0;

    private static int CountGenerated()
    {
        var asm = typeof(ProtoPortStatus).Assembly;
        return asm.GetTypes()
            .Count(t => t.Namespace == "Star"
                        && typeof(IMessage).IsAssignableFrom(t)
                        && !t.IsAbstract);
    }
}
