using Google.Protobuf;
using SaoAuto.Proto;
using Star;

namespace SaoAuto.ParityTests;

/// <summary>
/// Smoke tests proving the canonical Star.* protobuf bindings generated by
/// Grpc.Tools at build time are reachable, deterministic, and can round-trip
/// through serialize/parse.
/// </summary>
public class StarProtoSmokeTests
{
    [Fact]
    public void CodegenProducesStarMessages()
    {
        Assert.True(ProtoPortStatus.CodegenAvailable,
            "Grpc.Tools should generate at least one Star.* message at build time.");
        Assert.True(ProtoPortStatus.GeneratedMessageCount > 100,
            $"Expected hundreds of messages from canonical proto, got {ProtoPortStatus.GeneratedMessageCount}.");
    }

    [Fact]
    public void AttrRoundTripsThroughSerializer()
    {
        var attr = new Attr
        {
            Id = 4242,
            RawData = ByteString.CopyFromUtf8("笨猫ฅฅ"),
        };

        var bytes = attr.ToByteArray();
        var parsed = Attr.Parser.ParseFrom(bytes);

        Assert.Equal(attr.Id, parsed.Id);
        Assert.Equal(attr.RawData, parsed.RawData);
    }

    [Fact]
    public void AttrCollectionNestsMessages()
    {
        var coll = new AttrCollection { Uuid = 0x1234_5678_9ABC_DEF0L };
        coll.Attrs.Add(new Attr { Id = 1, RawData = ByteString.CopyFromUtf8("hp") });
        coll.Attrs.Add(new Attr { Id = 2, RawData = ByteString.CopyFromUtf8("mp") });

        var parsed = AttrCollection.Parser.ParseFrom(coll.ToByteArray());

        Assert.Equal(coll.Uuid, parsed.Uuid);
        Assert.Equal(2, parsed.Attrs.Count);
        Assert.Equal(1, parsed.Attrs[0].Id);
        Assert.Equal("mp", parsed.Attrs[1].RawData.ToStringUtf8());
    }
}
