<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <IsPackable>false</IsPackable>
    <RootNamespace>SaoAuto.IntegrationTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SaoAuto.App\SaoAuto.App.csproj" />
    <ProjectReference Include="..\..\src\SaoAuto.Core\SaoAuto.Core.csproj" />
    <ProjectReference Include="..\..\src\SaoAuto.MemProbe\SaoAuto.MemProbe.csproj" />
    <ProjectReference Include="..\..\src\SaoAuto.Overlay\SaoAuto.Overlay.csproj" />
    <ProjectReference Include="..\..\src\SaoAuto.UpdateHost\SaoAuto.UpdateHost.csproj" />
  </ItemGroup>

</Project>
