@echo off
chcp 65001 >nul 2>&1
setlocal enabledelayedexpansion

:: SAO-UI Nuitka Build -- one-click full pipeline
::
:: Layout:
::   dist\release\XiaoACTUI\
::     XiaoACTUI.exe          C launcher (10KB, no CRT)
::     runtime\XiaoACTUI.exe  Nuitka main EXE
::     web\ assets\ plugins\ locale\ docs\
::
:: Usage:  build_nuitka.bat [--clean]

set "ROOT=%~dp0"
pushd "%ROOT%"

set "DIST=%ROOT%dist"
set "NUITKA_OUT=%DIST%\nuitka\main.dist"
set "NUITKA_BUILD=%DIST%\nuitka\main.build"
set "RELEASE=%DIST%\release\XiaoACTUI"
set "LAUNCHER_OUT=%DIST%\launcher"

if "%~1"=="--clean" (
    echo [CLEAN] Clearing Nuitka C cache...
    if exist "%DIST%\nuitka" rmdir /s /q "%DIST%\nuitka"
    echo   Cache cleared.
)

:: ---- [0/7] Roslyn ----
echo [0/7] Ensuring Roslyn C# compiler DLLs...
if not exist "%ROOT%act_platform\scripting\roslyn\Microsoft.CodeAnalysis.CSharp.dll" (
    python -m act_platform.scripting.fetch_roslyn
    if errorlevel 1 (
        echo WARNING: Roslyn fetch failed, .cs plugin compilation will need .NET SDK
    )
) else (
    echo   OK: Roslyn DLLs already present
)

:: ---- [1/7] Cython ----
echo [1/7] Building Cython accelerators...
python build_cython_ext.py build_ext --inplace
if errorlevel 1 goto :fail

:: ---- [2/7] C launcher ----
:: 外层 launcher.c/launcher.rc 不在 → legacy 路径不可用，自动切 hardening 拆分路径
if not exist "%ROOT%launcher.rc" (
    if not "%SAO_ENABLE_HARDENING%"=="1" (
        echo   launcher.rc removed, auto-enabling hardening path
        set "SAO_ENABLE_HARDENING=1"
    )
)
if "%SAO_ENABLE_HARDENING%"=="1" (
    echo [2/7] Compiling multi-module native launcher ^(hardening enabled^)...
    call build_launcher.bat
    if errorlevel 1 goto :fail
    if exist "%LAUNCHER_OUT%\linkstart.exe" (
        copy /y "%LAUNCHER_OUT%\linkstart.exe" "%LAUNCHER_OUT%\XiaoACTUI.exe" >nul
    ) else (
        copy /y "%LAUNCHER_OUT%\linkstart_raw.exe" "%LAUNCHER_OUT%\XiaoACTUI.exe" >nul
    )
    echo   OK: hardened launcher assembled
) else (
    echo [2/7] Compiling C launcher ^(legacy single-file mode^)...
    set "VSWHERE=!ProgramFiles(x86)!\Microsoft Visual Studio\Installer\vswhere.exe"
    if not exist "!VSWHERE!" (
        echo ERROR: vswhere.exe not found
        goto :fail
    )
    for /f "usebackq tokens=*" %%i in (`"!VSWHERE!" -latest -products * -property installationPath`) do set "VSDIR=%%i"
    if not defined VSDIR (
        echo ERROR: Visual Studio not found
        goto :fail
    )
    call "!VSDIR!\VC\Auxiliary\Build\vcvarsall.bat" x64 >nul 2>&1
    if not exist "%LAUNCHER_OUT%" mkdir "%LAUNCHER_OUT%"
    rc /nologo launcher.rc
    if errorlevel 1 goto :fail
    cl /nologo /O2 /GS- launcher.c launcher.res /Fe:"%LAUNCHER_OUT%\XiaoACTUI.exe" /link kernel32.lib
    if errorlevel 1 goto :fail
    del /q launcher.res launcher.obj >nul 2>&1
    echo   OK: %LAUNCHER_OUT%\XiaoACTUI.exe
)

:: ---- [2b/7] Seal constants + freeze build_id (hardening only) ----
if "%SAO_ENABLE_HARDENING%"=="1" (
    echo [2b/7] Freezing build_id + sealing constants...
    if not defined SAO_BUILD_ID (
        for /f "usebackq tokens=*" %%V in (`python -c "from config import APP_VERSION;print(APP_VERSION)"`) do set "_APP_VER=%%V"
        for /f "usebackq tokens=*" %%G in (`git rev-parse --short HEAD 2^>nul`) do set "_GIT_SHORT=%%G"
        if not defined _GIT_SHORT set "_GIT_SHORT=nogit"
        set "SAO_BUILD_ID=!_APP_VER!-!_GIT_SHORT!"
    )
    echo   build_id: !SAO_BUILD_ID!
    > license\_build_id.py echo # Auto-generated by build_nuitka.bat hardening stage; do not edit
    >> license\_build_id.py echo BUILD_ID = "!SAO_BUILD_ID!"

    python license\tests\seal_constants.py ^
        --server-url "%SAO_SERVER_URL%" ^
        --update-host "%SAO_UPDATE_HOST%" ^
        --server-pubkey "%SAO_SERVER_ED25519_PUBKEY%" ^
        --cert-pin-primary "%SAO_CERT_PIN_PRIMARY%" ^
        --cert-pin-backup "%SAO_CERT_PIN_BACKUP%"
    if errorlevel 1 (
        echo WARNING: seal_constants failed; hardening disabled for this build
        set "SAO_ENABLE_HARDENING="
    )
)

:: ---- [3/7] Nuitka ----
echo [3/7] Nuitka compilation...
if exist "%NUITKA_OUT%" rmdir /s /q "%NUITKA_OUT%"

:: AI Editor real terminal PTY (pywinpty, optional dependency). Only the
:: Python modules need explicit inclusion (imported conditionally, so the
:: import follower misses them). The four native binaries (conpty.dll,
:: winpty.dll, OpenConsole.exe, winpty-agent.exe) are auto-bundled by
:: Nuitka's dll-files plugin (built-in winpty package config); listing them
:: again via --include-data-files makes the build fail with a conflict.
:: cv2's opencv_videoio ffmpeg DLL is covered the same way.
set "WINPTY_NUITKA_FLAGS="
set "WINPTY_DIR="
for /f "usebackq tokens=*" %%W in (`python -c "import importlib.util as u,os; s=u.find_spec('winpty'); print(os.path.dirname(s.origin)) if s and s.origin else print('')" 2^>nul`) do set "WINPTY_DIR=%%W"
if defined WINPTY_DIR if not "%WINPTY_DIR%"=="" (
    echo   pywinpty found, including winpty modules
    set "WINPTY_NUITKA_FLAGS=--include-module=winpty --include-module=winpty.ptyprocess --include-module=winpty.enums"
) else (
    echo   pywinpty not installed - this build will fall back to pipe-mode terminal only
)

:: Localized MSVC (Chinese-only clui resources) emits diagnostics in the
:: console codepage; under chcp 65001 that is UTF-8, which Nuitka's scons
:: decodes as mbcs (cp936) and crashes with UnicodeDecodeError. Match the
:: console CP to the ANSI CP for the compile, restore afterwards.
chcp 936 >nul 2>&1
python -m nuitka --standalone --assume-yes-for-downloads --windows-console-mode=disable --windows-icon-from-ico=icon.ico --windows-uac-admin --output-dir=%DIST%\nuitka --output-filename=XiaoACTUI.exe --no-prefer-source-code --no-deployment-flag=excluded-module-usage --enable-plugin=tk-inter --include-package=gui_modules --include-package=utils --include-package=render --include-package=updater --include-package=sao_theme --include-package=act_platform --include-package=ui_gpu --include-package=ai_editor --include-package=workshop --include-package=license --include-package=mem_probe --nofollow-import-to=mem_probe.rt_io --include-module=sao_gui --include-module=sao_webview --include-module=win32crypt --include-module=pywintypes --include-package=google.protobuf --include-package=clr_loader --include-module=clr --include-module=pythonnet --include-module=pygame --include-module=pygame.mixer --include-module=pygame._sdl2 --include-module=cv2 --include-module=PIL.Image --include-module=PIL.ImageDraw --include-module=PIL.ImageFont --include-module=PIL.ImageFilter --include-module=mss --include-module=mss.windows --include-module=windows_capture --include-module=pynput --include-module=pynput.keyboard --include-module=pynput.keyboard._win32 --include-module=pynput.mouse --include-module=pynput.mouse._win32 --include-module=moderngl --include-module=moderngl_window --include-module=moderngl_window.context.headless --include-module=skia --include-module=zstandard --include-package=lupa --include-data-files=act_platform/scripting/roslyn/*.dll=act_platform/scripting/roslyn/ %WINPTY_NUITKA_FLAGS% --nofollow-import-to=httpx._main --nofollow-import-to=matplotlib --nofollow-import-to=scipy --nofollow-import-to=pandas --nofollow-import-to=torch --nofollow-import-to=tensorflow --nofollow-import-to=test --nofollow-import-to=unittest --nofollow-import-to=xmlrpc --nofollow-import-to=doctest --nofollow-import-to=pydoc --nofollow-import-to=webview.platforms.android --nofollow-import-to=webview.platforms.gtk --nofollow-import-to=webview.platforms.cocoa --nofollow-import-to=webview.platforms.qt --nofollow-import-to=ai_editor.selftest --jobs=8 main.py
set "NUITKA_RC=%errorlevel%"
chcp 65001 >nul 2>&1
if not "%NUITKA_RC%"=="0" (
    echo ERROR: Nuitka compilation failed
    goto :fail
)

:: ---- [3b/7] Build helper (rt_io isolated process) ----
echo [3b/7] Building rt_io helper...
:: Nuitka's Windows version fields require exactly four numeric components.
:: APP_VERSION remains the product-facing version; normalize it for this helper.
chcp 65001 >nul 2>&1
set "HELPER_FILE_VERSION=1.0.0.0"
for /f "usebackq delims=" %%V in (`python -c "from config import APP_VERSION; parts=str(APP_VERSION).strip().split('.'); valid=1 ^<= len(parts) ^<= 4 and all(part.isdigit() and int(part) ^<= 65535 for part in parts); print('.'.join((parts + ['0'] * 4)[:4]) if valid else 1/0)" 2^>nul`) do set "HELPER_FILE_VERSION=%%V"
echo   Helper file version: !HELPER_FILE_VERSION!
chcp 936 >nul 2>&1
python -m nuitka --standalone --assume-yes-for-downloads --windows-console-mode=disable --windows-icon-from-ico=icon.ico --windows-company-name="SAO Auto" --windows-product-name="SAO Auto" --windows-file-description="SAO Auto helper subprocess" --windows-file-version=!HELPER_FILE_VERSION! --windows-product-version=!HELPER_FILE_VERSION! --output-dir=%DIST%\nuitka_helper --output-filename=SaoUiHelper.exe --no-prefer-source-code --include-package=mem_probe --nofollow-import-to=mem_probe.rt_io_proxy --nofollow-import-to=gui_modules --nofollow-import-to=render --nofollow-import-to=sao_gui --nofollow-import-to=sao_webview --nofollow-import-to=act_platform --nofollow-import-to=ui_gpu --nofollow-import-to=ai_editor --nofollow-import-to=workshop --jobs=8 mem_probe\_rt_io_helper_entry.py
set "HELPER_RC=%errorlevel%"
chcp 65001 >nul 2>&1
if not "%HELPER_RC%"=="0" (
    echo ERROR: Helper build failed
    goto :fail
)
set "HELPER_OUT=%DIST%\nuitka_helper\_rt_io_helper_entry.dist"

if not exist "%HELPER_OUT%\SaoUiHelper.exe" (
    echo ERROR: Helper executable was not produced
    goto :fail
)

:: ---- [3c/7] Harden helper ----
if exist "%HELPER_OUT%\SaoUiHelper.exe" (
    echo [3c/7] Hardening helper binaries...
    python post_build_harden.py "%HELPER_OUT%"
) else (
    echo [3c/7] Helper not built, skipping harden
)

:: ---- [4/7] Assemble ----
echo [4/7] Assembling release layout...
if exist "%RELEASE%" rmdir /s /q "%RELEASE%"
mkdir "%RELEASE%"
mkdir "%RELEASE%\runtime"
mkdir "%RELEASE%\temp"
mkdir "%RELEASE%\user_plugins"

copy /y "%LAUNCHER_OUT%\XiaoACTUI.exe" "%RELEASE%\linkstart.exe" >nul
xcopy /e /i /y /q "%NUITKA_OUT%\*" "%RELEASE%\runtime\" >nul

:: Copy the helper subprocess executable into the runtime directory.
if exist "%HELPER_OUT%\SaoUiHelper.exe" (
    xcopy /e /i /y /q "%HELPER_OUT%\*" "%RELEASE%\runtime\helper\" >nul
    echo   Helper subprocess packaged as runtime\helper\SaoUiHelper.exe
    :: Mirror sealed/wbox next to helper so its license bootstrap can find them
    :: via the sys.executable-neighbor fallback in _bootstrap._exe_neighbor_paths.
    if exist "%ROOT%license\sealed_constants.bin" copy /y "%ROOT%license\sealed_constants.bin" "%RELEASE%\runtime\helper\" >nul
    if exist "%ROOT%license\wbox_tables.bin"      copy /y "%ROOT%license\wbox_tables.bin"      "%RELEASE%\runtime\helper\" >nul
)

if not exist "%RELEASE%\runtime\helper\SaoUiHelper.exe" (
    echo ERROR: Helper executable was not assembled into the runtime layout
    goto :fail
)

if exist "%RELEASE%\runtime\web" (
    xcopy /e /i /y /q "%RELEASE%\runtime\web" "%RELEASE%\web\" >nul
    rmdir /s /q "%RELEASE%\runtime\web"
)
if exist "%RELEASE%\runtime\assets" (
    xcopy /e /i /y /q "%RELEASE%\runtime\assets" "%RELEASE%\assets\" >nul
    rmdir /s /q "%RELEASE%\runtime\assets"
)

:: Copy sealed constants and wbox tables — both consumers need their own copy:
::   runtime\             — launcher_main.c reads with hard-coded relative paths
::   runtime\license\     — Python _bootstrap.py resolves relative to license pkg
:: Keep both. Removing one to "dedupe" will break the corresponding consumer silently.
if "%SAO_ENABLE_HARDENING%"=="1" (
    if not exist "%RELEASE%\runtime\license" mkdir "%RELEASE%\runtime\license" >nul 2>&1
    if exist "%ROOT%license\sealed_constants.bin" (
        copy /y "%ROOT%license\sealed_constants.bin" "%RELEASE%\runtime\" >nul
        copy /y "%ROOT%license\sealed_constants.bin" "%RELEASE%\runtime\license\" >nul
    )
    if exist "%ROOT%license\wbox_tables.bin" (
        copy /y "%ROOT%license\wbox_tables.bin"      "%RELEASE%\runtime\" >nul
        copy /y "%ROOT%license\wbox_tables.bin"      "%RELEASE%\runtime\license\" >nul
    )
)

if exist "%ROOT%web" xcopy /e /i /y /q "%ROOT%web" "%RELEASE%\web\" >nul
if exist "%ROOT%assets" xcopy /e /i /y /q "%ROOT%assets" "%RELEASE%\assets\" >nul
if exist "%ROOT%plugins" xcopy /e /i /y /q "%ROOT%plugins" "%RELEASE%\plugins\" >nul
if exist "%ROOT%locale" xcopy /e /i /y /q "%ROOT%locale" "%RELEASE%\locale\" >nul
if exist "%ROOT%docs" xcopy /e /i /y /q "%ROOT%docs" "%RELEASE%\docs\" >nul
if exist "%ROOT%icon.ico" copy /y "%ROOT%icon.ico" "%RELEASE%\" >nul

:: ---- [5/7] Harden ----
echo [5/7] Post-build hardening (runtime/)...
python post_build_harden.py "%RELEASE%\runtime"

:: ---- [5b/7] Runtime DLL SHA-256 manifest (hardening only) ----
if "%SAO_ENABLE_HARDENING%"=="1" (
    echo [5b/7] Hashing runtime DLLs into manifest...
    if not exist "%ROOT%build" mkdir "%ROOT%build"
    python license\tests\hash_runtime_dlls.py "%RELEASE%\runtime" --out "%ROOT%build\runtime_manifest.json"
    if errorlevel 1 echo WARNING: hash_runtime_dlls failed
)

:: ---- [5c/7] Hook baseline (hardening only) ----
if "%SAO_ENABLE_HARDENING%"=="1" (
    echo [5c/7] Capturing hook baseline...
    python license\tests\gen_hook_baseline.py --out "%ROOT%build\hook_baseline.json"
    if errorlevel 1 echo WARNING: gen_hook_baseline failed
)

:: ---- [6/7] Verify ----
echo [6/7] Roslyn in distribution check...
if exist "%RELEASE%\runtime\act_platform\scripting\roslyn\Microsoft.CodeAnalysis.CSharp.dll" (
    echo   OK: Roslyn compiler bundled
) else (
    echo   WARNING: Roslyn DLLs not found in distribution
)
if defined WINPTY_DIR if not "%WINPTY_DIR%"=="" (
    if exist "%RELEASE%\runtime\winpty\conpty.dll" (
        echo   OK: ConPTY binaries bundled
    ) else (
        echo   WARNING: winpty native binaries missing - PTY terminal will fall back to pipe mode
    )
)

:: ---- [7/7] Verify ----
echo [7/7] Verify
echo.
for %%F in ("%RELEASE%\linkstart.exe") do echo   Launcher: %%~zF bytes
for %%F in ("%RELEASE%\runtime\XiaoACTUI.exe") do echo   Runtime:  %%~zF bytes
echo.
echo BUILD OK
popd
exit /b 0

:fail
echo BUILD FAILED
popd
exit /b 1
