#pragma once

#define SAO_UI_SOUND_ASSET_CLICK 601
#define SAO_UI_SOUND_ASSET_MENU_OPEN 602
#define SAO_UI_SOUND_ASSET_MENU_CLOSE 603
#define SAO_UI_SOUND_ASSET_PANEL 604
#define SAO_UI_SOUND_ASSET_SUBMENU 605
#define SAO_UI_SOUND_ASSET_ALERT 606
#define SAO_UI_SOUND_ASSET_ALERT_CLOSE 607
#define SAO_UI_SOUND_ASSET_WELCOME 608
#define SAO_UI_SOUND_ASSET_ALO_WELCOME 609
#define SAO_UI_SOUND_ASSET_LINK_START 610
#define SAO_UI_SOUND_ASSET_NERVEGEAR 611
#define SAO_UI_SOUND_ASSET_MESSAGE 612
#define SAO_UI_SOUND_ASSET_SYSTEM 613
#define SAO_UI_SOUND_ASSET_WARNING 614
#define SAO_UI_SOUND_ASSET_EMERGENCY 615
